🌐 Add Chinese translation for `docs/zh/docs/tutorial/background-tasks.md`
tiangolo/fastapi pull request #9812
Opened 2023-07-05 12:09 UTC by wdh99

Outdate pull request: #2464 #3827

2023-07-05 12:14 UTC, tiangolo commented
📝 Docs preview for commit 01e682aa457f0cda83ca301c886d1f9bf3b7e6d8 at: https://64a55e60c2150e06966d6dc5--fastapi.netlify.app

2023-07-06 03:05 UTC, mkdir700 requested changes
Some sentences have not been translated.

2023-07-06 03:05 UTC, mkdir700 commented on docs/zh/docs/tutorial/background-tasks.md
> +        Prefer to use the `Annotated` version if possible.
```suggestion
        尽可能选择使用 `Annotated` 的版本。
```

2023-07-06 03:05 UTC, mkdir700 commented on docs/zh/docs/tutorial/background-tasks.md
> +        Prefer to use the `Annotated` version if possible.
```suggestion
        尽可能选择使用 `Annotated` 的版本。
```

2023-07-06 11:43 UTC, wdh99 commented on docs/zh/docs/tutorial/background-tasks.md
> +        Prefer to use the `Annotated` version if possible.
已修改

2023-07-06 11:47 UTC, tiangolo commented
📝 Docs preview for commit dbf65f98da84749cd6b29ae7180fafd7f0a6aecf at: https://64a6a9b09810b61cb9d3ec7e--fastapi.netlify.app

2023-07-06 12:50 UTC, mkdir700 commented on docs/zh/docs/tutorial/background-tasks.md
> +但是，如果您需要从同一个**FastAPI**应用程序访问变量和对象，或者您需要执行小型后台任务（如发送电子邮件通知），您只需使用 `BackgroundTasks` 即可。
```suggestion
但是，如果您需要从同一个 **FastAPI** 应用程序访问变量和对象，或者您需要执行小型后台任务（如发送电子邮件通知），您只需使用 `BackgroundTasks` 即可。
```

2023-07-10 08:25 UTC, mahone3297 commented on docs/zh/docs/tutorial/background-tasks.md
> +你可以定义后台任务，在返回响应之后运行。
或者这样？“你可以定义后台任务，这些任务会在相应返回后运行。”

2023-07-10 11:17 UTC, wdh99 commented on docs/zh/docs/tutorial/background-tasks.md
> +通过仅使用 `BackgroundTasks` (而不是 `BackgroundTask`)，使得能将它作为 *路径操作函数* 的参数 ，并让**FastAPI**为您处理其余部分, 就像直接使用 `Request` 对象。
这里采用了加粗, 所以我人为可以不加空格

2023-07-10 11:17 UTC, wdh99 commented on docs/zh/docs/tutorial/background-tasks.md
> +首先导入 `BackgroundTasks` 并在 *路径操作函数* 中使用类型声明`BackgroundTasks`定义一个参数：
√

2023-07-10 11:18 UTC, wdh99 commented on docs/zh/docs/tutorial/background-tasks.md
> +你可以定义后台任务，在返回响应之后运行。
√

2023-07-10 11:21 UTC, wdh99 commented on docs/zh/docs/tutorial/background-tasks.md
> +如果您需要执行繁重的后台计算，并且不一定需要由同一进程运行（例如，您不需要共享内存、变量等），那么使用其他更大的工具（如<a href="https://docs.celeryq.dev" class="external-link" target="_blank">Celery</a>）可能更好。
√

2023-07-10 11:23 UTC, wdh99 commented on docs/zh/docs/tutorial/background-tasks.md
> +要查看示例，查阅 [Project Generators](../project-generation.md){.internal-link target=_blank}，它们都包括已经配置的Celery。
这里采用了加粗, 所以我认为可以不加空格

2023-07-10 11:25 UTC, wdh99 commented on docs/zh/docs/tutorial/background-tasks.md
> +它们往往需要更复杂的配置，即消息/作业队列管理器，如RabbitMQ或Redis，但它们允许您在多个进程中运行后台任务，甚至是在多个服务器中。
这里短短几个字加了好几个空格, 看起来有些凌乱, 所以我认为不用加空格.

2023-07-10 11:26 UTC, wdh99 commented on docs/zh/docs/tutorial/background-tasks.md
> +要查看示例，查阅 [Project Generators](../project-generation.md){.internal-link target=_blank}，它们都包括已经配置的Celery。
英文单词出现在了最后面, 已经很清晰, 所以我认为不用加空格.

2023-07-11 07:12 UTC, lordqyxz approved these changes

2023-07-16 20:34 UTC, ChoyeonChern approved these changes

2023-07-27 18:55 UTC, tiangolo commented
Great, thank you @wdh99! 🙇 

And thanks for the reviews @mahone3297, @mkdir700, @lordqyxz, @ChoyeonChern 🍰

2023-07-27 18:55 UTC, merged